### PR TITLE
Fixed #18

### LINKED ISSUE #18: Ability to set pageSize
I have a use-case where I want to display results in increments other than 10. I don't see any way to change the pageSize for the initial request. It seems odd aggregation sizes can be set but query sizes cannot. Would it be difficult to implement a .size() option on queries?

### PR DESCRIPTION
**Pull request by lukewertz**
If you could, please review my code and let me know what improvements I should make. Thanks!

### CODE REVIEW

**Comment by YousefED** [comment]
Thanks, looks great! Could it be I'm missing SizeDirective.ts in the pull request btw?

If possible, would also be great if you could add eui-size to the example (perhaps with a dropdown) - so we can easily test the functionality of all components in the demo.

**Comment by lukewertz** [comment]
Thanks. I had not added the SizeDirective or SizeController files. That's what I get for working too late at night. I'll add a example to the demo file tonight or tomorrow.

Thanks for the feedback!

**Comment by lukewertz** [comment]
As a followup to this PR, it introduces an interesting issue. The concept of pagination is made more complicated by being able to configure the number of results per "page" (where "page" is really an artificial construct meant to represent a result set with an offset).

There are three ways that I could see this working:
* 1. When you are on a page (any page) and change your result set size, you are taken back to page 0.
* 2. When you are on a page (any page) and change your result set size, the index of the first item in the result set is tracked and the paginator is recomputed based on the index you were looking at.
* 3. When you are on a page (any page) and change your result set size, the thing that is tracked is the page you were on, so you would be taken to the paged result set equal to whatever page you were on with the different result set size (i.e.: "page 3" is "page 3" regardless of how many results are on each page)

As the code is written right now, option 3 is what is happening. Frankly, I think that is the worst of all three options.

I think the "best" solution would be for the index (offset) to be tracked and you continue browsing in the result set stream where you were when you changed the page size. That's probably harder than treating the result set size as a fundamental property of the query and treating a change in page result set size as the instantiation of a new query (that is: going back to page 0).

I'm very open to input on this topic.

**Comment by YousefED** [comment]
I think there is no clear winner between option 1 and 2 (I've seen both on large websites). I'd suggest using option 1 (I think it fits better for a general purpose library like this and is easier to implement).

Re. the PR, would you mind adding eui-size to the demo file as discussed before?

Thanks!

**Comment by lukewertz** [comment]
Yes. It was in adding it to the demo file that I surfaced the issue.

The commit that adds the demo is here: https://github.com/lukewertz/ElasticUI/commit/236bfcedbc8544dbfe99ed3510ccf38b5a5b846d

I have not yet resolved the issue in comment https://github.com/YousefED/ElasticUI/pull/19#issuecomment-84396797

**Comment by fsattar** [comment]
@YousefED Are there plans to resolve this PR? I have a similar use case which requires varying page size.

**Pull request closed without merging**
